Repository microsoft/AdaptiveCards, pull requests merged in 2020-06, with the labels that each got.

#4124 [JS] Prevent factsets from presenting as tables for accessibility
  source/nodejs/ac-typed-schema/package-lock.json
  source/nodejs/aclint/package-lock.json
  source/nodejs/adaptivecards-controls/package-lock.json
  source/nodejs/adaptivecards-designer-app/package-lock.json
  source/nodejs/adaptivecards-designer/package-lock.json
  source/nodejs/adaptivecards-site/package-lock.json
  source/nodejs/adaptivecards-site/themes/adaptivecards/package-lock.json
  source/nodejs/adaptivecards-templating/package-lock.json
  source/nodejs/adaptivecards-visualizer/package-lock.json
  source/nodejs/adaptivecards/src/card-elements.ts
  source/nodejs/package-lock.json
  source/nodejs/spec-generator/package-lock.json
Labels: Area-Accessibility, Platform-HTML

#4133 [Designer] Accessibility updates for designer new sample dialog
  source/nodejs/adaptivecards-designer/src/dialog.ts
  source/nodejs/adaptivecards-designer/src/open-sample-dialog.ts
Labels: Area-Accessibility, Platform-HTML

#4120 [UWP] Cherry-pick visibility fixes to release
  source/uwp/AdaptiveCardTestApp/Expected/Fixed Size Non-Interactive.v1.0.Elements.FactSet.Markdown.png
  source/uwp/AdaptiveCardTestApp/Expected/Fixed Size Non-Interactive.v1.0.Tests.TextBlock.Markdown.Telephony.png
  source/uwp/AdaptiveCardTestApp/Expected/Fixed Size Non-Interactive.v1.2.Elements.Column.Fallback.png
  source/uwp/AdaptiveCardTestApp/Expected/Fixed Size Non-Interactive.v1.2.Tests.AdaptiveCard.BackgroundImage.FillMode.Cover.SmallImage.png
  source/uwp/AdaptiveCardTestApp/Expected/Fixed Size Non-Interactive.v1.2.Tests.ContainerDoubleFallback.png
  source/uwp/AdaptiveCardTestApp/Expected/No host config (default values).v1.0.Elements.FactSet.Markdown.png
  source/uwp/AdaptiveCardTestApp/Expected/No host config (default values).v1.0.Tests.TextBlock.Markdown.Telephony.png
  source/uwp/AdaptiveCardTestApp/Expected/No host config (default values).v1.2.Elements.Column.Fallback.png
  source/uwp/AdaptiveCardTestApp/Expected/No host config (default values).v1.2.Tests.AdaptiveCard.BackgroundImage.FillMode.Cover.SmallImage.png
  source/uwp/AdaptiveCardTestApp/Expected/No host config (default values).v1.2.Tests.ContainerDoubleFallback.png
  source/uwp/AdaptiveCardTestApp/Expected/testVariantHostConfig.v1.0.Elements.FactSet.Markdown.png
  source/uwp/AdaptiveCardTestApp/Expected/testVariantHostConfig.v1.0.Tests.TextBlock.Markdown.Telephony.png
  source/uwp/AdaptiveCardTestApp/Expected/testVariantHostConfig.v1.2.Elements.Column.Fallback.png
  source/uwp/AdaptiveCardTestApp/Expected/testVariantHostConfig.v1.2.Tests.AdaptiveCard.BackgroundImage.FillMode.Cover.SmallImage.png
  source/uwp/AdaptiveCardTestApp/Expected/testVariantHostConfig.v1.2.Tests.ContainerDoubleFallback.png
  source/uwp/Renderer/lib/ElementTagContent.cpp
  source/uwp/Renderer/lib/ElementTagContent.h
  source/uwp/Renderer/lib/XamlBuilder.cpp
Labels: Platform-UWP

#4155 A couple of site updates for accessibility
  source/nodejs/adaptivecards-site/themes/adaptivecards/layout/index.ejs
  source/nodejs/adaptivecards-site/themes/adaptivecards/layout/sample.ejs
  source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css
Labels: Area-Accessibility

#4157 [JS] Add aria-expanded state to showcard action button
  source/nodejs/adaptivecards/docs/classes/action.md
  source/nodejs/adaptivecards/docs/classes/httpaction.md
  source/nodejs/adaptivecards/docs/classes/openurlaction.md
  source/nodejs/adaptivecards/docs/classes/showcardaction.md
  source/nodejs/adaptivecards/docs/classes/submitaction.md
  source/nodejs/adaptivecards/docs/classes/togglevisibilityaction.md
  source/nodejs/adaptivecards/src/card-elements.ts
Labels: Area-Accessibility, Platform-HTML

#4160 [Site] Opt out of tabIndex generation in samples and designer
  source/nodejs/adaptivecards-designer/src/card-designer.ts
  source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js
Labels: Area-Accessibility

#4171 [Designer] Add aria attributes to dropdown controls
  source/nodejs/adaptivecards-controls/src/dropdown.ts
  source/nodejs/adaptivecards-controls/src/inputwithpopup.ts
  source/nodejs/adaptivecards-controls/src/popupmenu.ts
  source/nodejs/adaptivecards-designer/src/toolbar.ts
Labels: AdaptiveCards v1.2.10, Area-Accessibility, Platform-HTML

#4173 [Site] Fix sticky sidebar math
  source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js
Labels: Area-Accessibility

#4174 [Site] Update copy code aria label
  source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/helper-code-and-card.js
Labels: Area-Accessibility

#4178 [Site] Remove superfluous link on article subtitles
  source/nodejs/adaptivecards-site/themes/adaptivecards/layout/archive.ejs
  source/nodejs/adaptivecards-site/themes/adaptivecards/source/css/style.css
Labels: Area-Accessibility

#4179 [Designer] Improve show/hide accessibility and labels
  source/nodejs/adaptivecards-controls/src/constants.ts
  source/nodejs/adaptivecards-designer/src/base-tree-item.ts
  source/nodejs/adaptivecards-designer/src/tool-box.ts
  source/nodejs/adaptivecards-designer/src/tree-view.ts
Labels: Area-Accessibility

#4177 [Site] Remove visualizer link in Designer
  source/nodejs/adaptivecards-site/themes/adaptivecards/layout/designer.ejs
Labels: Area-Accessibility

#4182 [JS] Fix aria accessibility for media element
  samples/v1.1/Scenarios/ProductVideo.json
  source/nodejs/adaptivecards/src/card-elements.ts
Labels: AdaptiveCards v1.2.10, Area-Accessibility

#4184 [JS] Express action sets as collections
  source/nodejs/adaptivecards/src/card-elements.ts
Labels: AdaptiveCards v1.2.10, Area-Accessibility

#4189 [Site] Fix markdown for version label on properties
  source/nodejs/ac-typed-schema/src/markdown/generate-markdown.ts
Labels: Area-Accessibility

#4193 Replace base64 decode map with an array to improve performance
  source/shared/cpp/ObjectModel/AdaptiveBase64Util.cpp
Labels: AdaptiveCards v1.2.10

#4207 [Designer] Change icon and error background colors for contrast
  source/nodejs/adaptivecards-designer/src/adaptivecards-designer.css
Labels: AdaptiveCards v1.2.10, Area-Accessibility

#4206 Update default hostconfigs for color contrast
  samples/HostConfig/outlook-desktop.json
  samples/HostConfig/render-to-image.json
  samples/HostConfig/sample.json
  samples/HostConfig/skype.json
  samples/HostConfig/webchat.json
  samples/HostConfig/windows-notification.json
  source/community/reactnative/App.js
  source/community/reactnative/src/utils/host-config.js
  source/community/reactnative/src/visualizer/segmented-control.js
  source/dotnet/Test/AdaptiveCards.Test/HostConfigApiTests.cs
  source/ios/AdaptiveCards/ADCIOSVisualizer/resources/filebrowserHostConfig.json
  source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
  source/nodejs/adaptivecards-designer/src/miscellaneous.ts
  source/nodejs/adaptivecards-site/themes/adaptivecards/source/js/script.js
  source/nodejs/adaptivecards-visualizer/src/constants.ts
  source/nodejs/adaptivecards-visualizer/src/containers/headless.ts
  source/nodejs/adaptivecards/docs/README.md
  source/nodejs/adaptivecards/docs/classes/containerstyledefinition.md
  source/nodejs/adaptivecards/src/host-config.ts
  source/pic2card/ui/src/components/config.js
  source/tools/hostConfig/json-to-scss/test.js
  source/vscode/src/adaptiveCardProvider.ts
Labels: AdaptiveCards v1.2.10, Area-Accessibility

#4218 Remove try-catch from ParseUtil::GetBackgroundImage and other small fixes
  source/shared/cpp/ObjectModel/BaseActionElement.h
  source/shared/cpp/ObjectModel/BaseCardElement.h
  source/shared/cpp/ObjectModel/BaseElement.cpp
  source/shared/cpp/ObjectModel/BaseElement.h
  source/shared/cpp/ObjectModel/BaseInputElement.h
  source/shared/cpp/ObjectModel/Inline.cpp
  source/shared/cpp/ObjectModel/Inline.h
  source/shared/cpp/ObjectModel/ParseUtil.cpp
  source/shared/cpp/ObjectModel/ParseUtil.h
  source/shared/cpp/ObjectModel/TextRun.h
  source/uwp/Renderer/lib/Util.cpp
Labels: Area-Performance

#4227 [JS] Updates for node dependencies
  source/nodejs/ac-typed-schema/package-lock.json
  source/nodejs/ac-typed-schema/package.json
  source/nodejs/aclint/package-lock.json
  source/nodejs/aclint/package.json
  source/nodejs/adaptivecards-controls/package-lock.json
  source/nodejs/adaptivecards-controls/package.json
  source/nodejs/adaptivecards-controls/webpack.config.js
  source/nodejs/adaptivecards-designer-app/package-lock.json
  source/nodejs/adaptivecards-designer-app/package.json
  source/nodejs/adaptivecards-designer-app/webpack.config.js
  source/nodejs/adaptivecards-designer/package-lock.json
  source/nodejs/adaptivecards-designer/package.json
  source/nodejs/adaptivecards-designer/webpack.config.js
  source/nodejs/adaptivecards-fabric/README.md
  source/nodejs/adaptivecards-fabric/package-lock.json
  source/nodejs/adaptivecards-fabric/package.json
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputChoiceSetFabric.test.tsx
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputDateFabric.test.tsx
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputTextFabric.test.tsx
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputTimeFabric.test.tsx
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/InputToggleFabric.test.tsx
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/__snapshots__/InputChoiceSetFabric.test.tsx.snap
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/__snapshots__/InputDateFabric.test.tsx.snap
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/__snapshots__/InputTextFabric.test.tsx.snap
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/__snapshots__/InputTimeFabric.test.tsx.snap
  source/nodejs/adaptivecards-fabric/src/__tests__/Components/Inputs/__snapshots__/InputToggleFabric.test.tsx.snap
  source/nodejs/adaptivecards-fabric/src/actions/ActionButton.tsx
  source/nodejs/adaptivecards-fabric/src/components/Fabric.tsx
  source/nodejs/adaptivecards-fabric/src/components/inputs/InputChoiceSetFabric.tsx
  source/nodejs/adaptivecards-fabric/src/components/inputs/InputDateFabric.tsx
  source/nodejs/adaptivecards-fabric/src/components/inputs/InputNumberFabric.tsx
  source/nodejs/adaptivecards-fabric/src/components/inputs/InputTextFabric.tsx
  source/nodejs/adaptivecards-fabric/src/components/inputs/InputTimeFabric.tsx
  source/nodejs/adaptivecards-fabric/src/components/inputs/InputToggleFabric.tsx
  source/nodejs/adaptivecards-fabric/src/utils/shared.tsx
  source/nodejs/adaptivecards-fabric/webpack.config.js
  source/nodejs/adaptivecards-site/_config.yml
  source/nodejs/adaptivecards-site/package-lock.json
  source/nodejs/adaptivecards-site/package.json
  source/nodejs/adaptivecards-site/themes/adaptivecards/package-lock.json
  source/nodejs/adaptivecards-site/themes/adaptivecards/package.json
  source/nodejs/adaptivecards-templating/package-lock.json
  source/nodejs/adaptivecards-templating/package.json
  source/nodejs/adaptivecards-visualizer/package-lock.json
  source/nodejs/adaptivecards-visualizer/package.json
  source/nodejs/adaptivecards/docs/classes/textrun.md
  source/nodejs/adaptivecards/docs/classes/versions.md
  source/nodejs/adaptivecards/package-lock.json
  source/nodejs/adaptivecards/package.json
  source/nodejs/package-lock.json
  source/nodejs/package.json
  source/nodejs/spec-generator/package-lock.json
  source/nodejs/spec-generator/package.json
Labels: Platform-HTML

#4190 [DevSpec] Updates to input validation spec
  schemas/src/AdaptiveCard.json
  source/uwp/Visualizer/ViewModel/MainPageViewModel.cs
  specs/DesignDiscussions/InputLabels.md
  specs/DesignDiscussions/InputValidation.md
  specs/DesignDiscussions/assets/InputLabels/InputLabelWithMiddleElement.PNG
  specs/DesignDiscussions/assets/InputLabels/InputRequiredHint.PNG
  specs/DesignDiscussions/assets/InputLabels/LabelDefault.PNG
  specs/DesignDiscussions/assets/InputLabels/Survey1.png
  specs/DesignDiscussions/assets/InputLabels/Survey2.png
  specs/DesignDiscussions/assets/InputLabels/Survey3.png
  specs/DesignDiscussions/assets/InputLabels/Survey4.png
  specs/DesignDiscussions/assets/InputValidation/BrokenToggleWizard.PNG
  specs/DesignDiscussions/assets/InputValidation/BrokenToggleWizard2.PNG
  specs/DesignDiscussions/assets/InputValidation/CardCascadeSample.png
  specs/DesignDiscussions/assets/InputValidation/ChoiceSetValidation.gif
  specs/DesignDiscussions/assets/InputValidation/ErrorMessageFacebook.PNG
  specs/DesignDiscussions/assets/InputValidation/ErrorMessageGoogle.PNG
  specs/DesignDiscussions/assets/InputValidation/ErrorMessageMSForms.PNG
  specs/DesignDiscussions/assets/InputValidation/ErrorMessageOutlook.PNG
  specs/DesignDiscussions/assets/InputValidation/ErrorMessageSurveyMonkey.PNG
  specs/DesignDiscussions/assets/InputValidation/ErrorMessageSurveyMonkey2.PNG
  specs/DesignDiscussions/assets/InputValidation/ErrorMessageTwitter.PNG
  specs/DesignDiscussions/assets/InputValidation/FoodOrder.gif
  specs/DesignDiscussions/assets/InputValidation/InputAssociationShowCard.gif
  specs/DesignDiscussions/assets/InputValidation/InputValidationExample.png
  specs/DesignDiscussions/assets/InputValidation/Inputtext.inlineaction.png
  specs/DesignDiscussions/assets/InputValidation/InternalShowCardValidation.gif
  specs/DesignDiscussions/assets/InputValidation/NoneExample.PNG
  specs/DesignDiscussions/assets/InputValidation/Optional.PNG
  specs/DesignDiscussions/assets/InputValidation/RenderingValidationFailed.PNG
  specs/DesignDiscussions/assets/InputValidation/Required.PNG
  specs/DesignDiscussions/assets/InputValidation/SimpleForm.PNG
  specs/DesignDiscussions/assets/InputValidation/ToggleWizard.gif
Labels: Spec

#4219 [UWP] Cherry pick base64 decode performance improvements
  source/shared/cpp/ObjectModel/AdaptiveBase64Util.cpp
Labels: Area-Performance

#4248 Updated text block to treat empty text string as invalid
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
Labels: AdaptiveCards v1.2.10

#4222 Added Support for Chevron in UIButton
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.mm
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButtonExpandable.xib
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm
Labels: AdaptiveCards v1.2.10

#4220 [UWP] Cherry pick JSON parsing performance improvements
  source/shared/cpp/ObjectModel/ParseUtil.cpp
Labels: Area-Performance
