Repository microsoft/AdaptiveCards, pull requests merged in 2021-04, with the labels that each got.

#5609 [JS] Lerna-audit updates for JS packages
  source/nodejs/ac-typed-schema/package-lock.json
  source/nodejs/ac-typed-schema/package.json
  source/nodejs/aclint/package-lock.json
  source/nodejs/adaptivecards-aaf-testapp/package-lock.json
  source/nodejs/adaptivecards-designer-app/package-lock.json
  source/nodejs/adaptivecards-designer/package-lock.json
  source/nodejs/adaptivecards-fabric/package-lock.json
  source/nodejs/adaptivecards-site/package-lock.json
  source/nodejs/adaptivecards-visualizer/package-lock.json
  source/nodejs/adaptivecards/package-lock.json
  source/nodejs/package-lock.json
  source/nodejs/spec-generator/package-lock.json
Labels: Platform-HTML

#5676 [Site] Process explorer element descriptions with markdown
  source/nodejs/adaptivecards-site/themes/adaptivecards/layout/explorer.ejs
Labels: Area-Website

#5732 [JS] Update npm package dependencies
  source/nodejs/ac-typed-schema/package.json
  source/nodejs/adaptivecards-aaf-testapp/package-lock.json
  source/nodejs/adaptivecards-controls/package-lock.json
  source/nodejs/adaptivecards-designer-app/package-lock.json
  source/nodejs/adaptivecards-designer/package-lock.json
  source/nodejs/adaptivecards-fabric/package-lock.json
  source/nodejs/adaptivecards-site/package-lock.json
  source/nodejs/adaptivecards-visualizer/package-lock.json
  source/nodejs/adaptivecards/package-lock.json
  source/nodejs/spec-generator/package-lock.json
Labels: Platform-HTML

#5424 [Designer][Accessibility] Put open showcard next in tab order
  source/nodejs/adaptivecards/src/card-elements.ts
Labels: Design Discussion - Needed
