Repository microsoft/AdaptiveCards, pull requests merged in 2021-11, with the labels that each got.

#6640 stretch background to fill the berlin container and fix margin/padding size problem
  source/nodejs/adaptivecards-designer/src/card-designer-surface.ts
  source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-dark.css
  source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container-light.css
  source/nodejs/adaptivecards-designer/src/containers/berlin/berlin-container.ts
Labels: Area-HostConfig

#6720 Jwoo/feature/carousel 4
  source/nodejs/adaptivecards/src/carousel.ts
  source/nodejs/tests/ui-tests/src/ui-tests.test.ts
Labels: Needs: Author Feedback

#6729 [UWP]: Update ObjectModelProjection.vcxproj to have control flow guard
  source/uwp/ObjectModelProjection/ObjectModelProjection.vcxproj
Labels: UWP
