Repository microsoft/AdaptiveCards, pull requests merged in 2021-10, with the labels that each got.

#6466 [.NET] Update to .NET 5
  source/dotnet/Samples/AdaptiveCards.Sample.Html/AdaptiveCards.Sample.Html.csproj
  source/dotnet/Samples/WPFVisualizer.PackageProject/AdaptiveCards.Sample.WPFVisualizer.PackageProject.wapproj
  source/dotnet/Samples/WPFVisualizer/AdaptiveCards.Sample.WPFVisualizer.csproj
  source/dotnet/Test/AdaptiveCards.Rendering.Html.Test/AdaptiveCards.Rendering.Html.Test.csproj
  source/dotnet/Test/AdaptiveCards.Templating.Test/AdaptiveCards.Templating.Test.csproj
  source/dotnet/Test/AdaptiveCards.Test/AdaptiveCards.Test.csproj
Labels: Platform-.NET

#6473 [iOS] Fixed UnitTest Breakage
  source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACFramework.h
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRDateTextField.mm
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputChoiceSetRenderer.mm
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTapGestureRecognizerFactory.h
  source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/AdaptiveCards.h
  source/ios/AdaptiveCards/Podfile
Labels: Needs: Author Feedback

#6476 [JS] Update nodejs dependencies ahead of schema 1.5 release
  source/nodejs/ac-typed-schema/package-lock.json
  source/nodejs/aclint/package-lock.json
  source/nodejs/aclint/package.json
  source/nodejs/adaptivecards-aaf-testapp/package-lock.json
  source/nodejs/adaptivecards-fabric/package-lock.json
  source/nodejs/adaptivecards-react/package-lock.json
  source/nodejs/adaptivecards-react/package.json
  source/nodejs/adaptivecards-react/typedoc.json
  source/nodejs/adaptivecards-site/package-lock.json
  source/nodejs/adaptivecards-templating/package-lock.json
  source/nodejs/adaptivecards-templating/package.json
  source/nodejs/adaptivecards-templating/typedoc.json
  source/nodejs/adaptivecards-visualizer/package-lock.json
  source/nodejs/adaptivecards/package-lock.json
  source/nodejs/adaptivecards/package.json
  source/nodejs/adaptivecards/typedoc.json
  source/nodejs/package-lock.json
  source/nodejs/package.json
  source/nodejs/spec-generator/package-lock.json
Labels: Platform-JavaScript
